version: '3.3'
services:
    shard3a:
        container_name: mongo-shard3a
        network_mode: mongo-shard
        command: mongod --port 27017 --shardsvr --replSet shard03
        image: mongo
    shard3b:
        container_name: mongo-shard3b
        network_mode: mongo-shard
        command: mongod --port 27017 --shardsvr --replSet shard03
        image: mongo
